# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95056f4a823b20b4462556d1b2c720629f60b859f468f050ed003b0bc522b72a2ffd5f3fa8b60b841853712836829005cbafb0120c86c057867125953ed649ef

test:
  secret_key_base: cce9ef7d97a349cf50f4904c009078d453e2af6418a610d02f4868da6d87814989384e57e15fc9ee622fe64b4145c14030bf2207c84324a50844fefbebc439e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
